"""create traffic analyses and records tables

Revision ID: 574751755ecb
Revises: 
Create Date: 2026-10-09 18:01:44.374034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574751755ecb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status_enum', native_enum=False), nullable=False),
    sa.Column('total_rows_received', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_analyses_created_at'), 'traffic_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_traffic_analyses_id'), 'traffic_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_analyses_status'), 'traffic_analyses', ['status'], unique=False)
    op.create_table('traffic_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_domain', sa.String(length=255), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('bytes_received', sa.BigInteger(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_uri', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('sni_hostname', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['traffic_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_analysis_id'), 'traffic_records', ['analysis_id'], unique=False)
    op.create_index('ix_traffic_records_analysis_timestamp', 'traffic_records', ['analysis_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_traffic_records_destination_domain'), 'traffic_records', ['destination_domain'], unique=False)
    op.create_index(op.f('ix_traffic_records_destination_ip'), 'traffic_records', ['destination_ip'], unique=False)
    op.create_index('ix_traffic_records_domain_timestamp', 'traffic_records', ['destination_domain', 'timestamp'], unique=False)
    op.create_index(op.f('ix_traffic_records_id'), 'traffic_records', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_records_sni_hostname'), 'traffic_records', ['sni_hostname'], unique=False)
    op.create_index(op.f('ix_traffic_records_source_ip'), 'traffic_records', ['source_ip'], unique=False)
    op.create_index(op.f('ix_traffic_records_timestamp'), 'traffic_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_records_timestamp'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_source_ip'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_sni_hostname'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_id'), table_name='traffic_records')
    op.drop_index('ix_traffic_records_domain_timestamp', table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_destination_ip'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_destination_domain'), table_name='traffic_records')
    op.drop_index('ix_traffic_records_analysis_timestamp', table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_analysis_id'), table_name='traffic_records')
    op.drop_table('traffic_records')
    op.drop_index(op.f('ix_traffic_analyses_status'), table_name='traffic_analyses')
    op.drop_index(op.f('ix_traffic_analyses_id'), table_name='traffic_analyses')
    op.drop_index(op.f('ix_traffic_analyses_created_at'), table_name='traffic_analyses')
    op.drop_table('traffic_analyses')
    # ### end Alembic commands ###
